# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int

#gpt-3.5-turbo-0125:
#  model_name: gpt-3.5-turbo-0125
#  endpoints: null
#  api_type: openai
#  parallel: 8

gpt-4-0314:
  model_name: gpt-4-0314
  endpoints:
    - api_base: https://openrouter.ai/api/v1
      api_key: xxx
  api_type: openai
  parallel: 8

gpt-4-1106-preview:
  model_name: gpt-4-1106-preview
  endpoints:
    - api_base: https://openrouter.ai/api/v1
      api_key: xxxx
  api_type: openai
  parallel: 8

heurist-openhermes-mixtral-8x7b-gptq:
  model_name: openhermes-mixtral-8x7b-gptq
  endpoints: null
  #   system_prompt: You are a helpful assistant.
  api_type: heurist
  parallel: 8

truth_model:
  model_name: /workspace/orangetin-OpenHermes-Mixtral-8x7B-GPTQ-specific-revision
  endpoints:
    - api_base: http://localhost:8000/v1
      api_key: abc
  api_type: openai
  parallel: 8

0x453e587e45fe9737d4bee9cfffdd44e57380eb27-5ml1863:
  model_name: openhermes-mixtral-8x7b-gptq
  miner_id: 0x453e587e45fe9737d4bee9cfffdd44e57380eb27-5ml1863
  endpoints: null
#  system_prompt: You are a helpful assistant.
  api_type: heurist
  parallel: 8

0x4d206c6253d55ba92faa73685ebc99af848c347e-659c05:
  model_name: openhermes-mixtral-8x7b-gptq
  miner_id: 0x4d206c6253d55ba92faa73685ebc99af848c347e-659c05
  endpoints: null
#  system_prompt: You are a helpful assistant.
  api_type: heurist
  parallel: 8

0x6cdfd42dbb740868019ce7538acc9c8c0d144df1-9af1d3:
  model_name: openhermes-mixtral-8x7b-gptq
  miner_id: 0x6cdfd42dbb740868019ce7538acc9c8c0d144df1-9af1d3
  endpoints: null
  #  system_prompt: You are a helpful assistant.
  api_type: heurist
  parallel: 8

dolphin-miner:
  model_name: dolphin-2.9-llama3-8b
  miner_id: 0x692a275fbc5a76eee43a835538fbd9fd3e386e66-8c063d
  endpoints: null
  #  system_prompt: You are a helpful assistant.
  api_type: heurist
  parallel: 8

mistral-7b:
  model_name: openhermes-2-pro-mistral-7b
  miner_id: 0x550fb77d74ab1cc9e4250b7b951ea76208fc8538-e7f841
  endpoints: null
  #  system_prompt: You are a helpful assistant.
  api_type: heurist
  parallel: 8
